### ISSUE TITLE
Make all unit tests pass with ADIOS branch

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#102]
The adios_support branch has been rebased with master branch recently, and it has been extensively tested on Cori and Titan with a high-resolution E3SM F case. Before we merge ADIOS branch to master we must make sure all unit tests pass. 

We can turn on PIO_TEST_CLOSE_OPEN_FOR_SYNC (cmake ... -DPIO_TEST_CLOSE_OPEN_FOR_SYNC:BOOL=ON ...) to allow close+open instead of sync in fortran tests (ADIOS does not support syncing data until the file is closed).

For failed tests, we need work with the ADIOS team to get the errors fixed.

**Comment by jayeshkrishna** [comment]
The current test results, run once in 2 days, with the adios branch is available on cdash - https://my.cdash.org/index.php?project=ACME_PIO&date=2018-07-30

**Comment by jayeshkrishna** [comment]
All PIO2 tests pass on the ADIOS branch (see https://my.cdash.org/index.php?project=ACME_PIO&date=2018-10-26).

Closing this issue.
