### ISSUE TITLE
PIO_TF_Get_undef_iotypes returns wrong IO types

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#119]
When we configure PIO2 with NetCDF but without PnetCDF, unit test pio_file_fail has an output with messed-up code:
`PIO_TF: Starting create_file_always_fail(¸Çcã^E^?`

SUBROUTINE PIO_TF_Get_undef_iotypes returns a list of undefined IO types. This list could be used by a test to make sure that PIO fails gracefully for undefined types. However, the conditional compilation statements in the following code are wrong. When _NETCDF is defined and _PNETCDF is not defined, iotypes is not set to PIO_iotype_pnetcdf as expected.

```
    i = 1
#ifndef _NETCDF
      ! netcdf
      iotypes(i) = PIO_iotype_netcdf
      iotype_descs(i) = "NETCDF"
      i = i + 1
#ifndef _PNETCDF
      ! pnetcdf
      iotypes(i) = PIO_iotype_pnetcdf
      iotype_descs(i) = "PNETCDF"
      i = i + 1
#endif
#ifndef _NETCDF4
      ! netcdf4p, netcdf4c
      iotypes(i) = PIO_iotype_netcdf4c
      iotype_descs(i) = "NETCDF4C"
      i = i + 1
      iotypes(i) = PIO_iotype_netcdf4p
      iotype_descs(i) = "NETCDF4P"
      i = i + 1
#endif
#endif
```

The code below has a similar issue and it returns an incorrect number of undefined IO types. If PIO2 is configured with serial NetCDF and PnetCDF, num_iotypes should be set to 2 (netcdf4p, netcdf4c) but it is set to 0 instead.

```
    ! First find the number of io types
    num_iotypes = 0
#ifndef _NETCDF
      ! netcdf
      num_iotypes = num_iotypes + 1
#ifndef _NETCDF4
      ! netcdf4p, netcdf4c
      num_iotypes = num_iotypes + 2
#endif
#endif
#ifndef _PNETCDF
      ! pnetcdf
      num_iotypes = num_iotypes + 1
#endif
```

PS, SUBROUTINE PIO_TF_Get_undef_nc_iotypes has the same issue.

**Comment by jayeshkrishna** [comment]
Looks like the #endif in the first case should be moved up,
```


    i = 1
#ifndef _NETCDF
      ! netcdf
      iotypes(i) = PIO_iotype_netcdf
      iotype_descs(i) = "NETCDF"
      i = i + 1
#endif
#ifndef _PNETCDF
      ! pnetcdf
      iotypes(i) = PIO_iotype_pnetcdf
      iotype_descs(i) = "PNETCDF"
      i = i + 1
#endif
#ifndef _NETCDF4
      ! netcdf4p, netcdf4c
      iotypes(i) = PIO_iotype_netcdf4c
      iotype_descs(i) = "NETCDF4C"
      i = i + 1
      iotypes(i) = PIO_iotype_netcdf4p
      iotype_descs(i) = "NETCDF4P"
      i = i + 1
#endif


```

**Comment by jayeshkrishna** [comment]
The second case, finding the number of undefined iotypes seems to be correct

**Comment by jayeshkrishna** [comment]
The code assumes _NETCDF is defined if _NETCDF4 is defined.

**Comment by dqwu** [comment]
It is possible that _NETCDF is defined but _NETCDF4 is not defined (use serial NetCDF).
Then the second case is incorrect (result should be 2 but it is 0)

 ```
   num_iotypes = 0
#ifndef _NETCDF
      ! netcdf
      num_iotypes = num_iotypes + 1
#ifndef _NETCDF4
      ! netcdf4p, netcdf4c
      num_iotypes = num_iotypes + 2
#endif
#endif
```

**Comment by dqwu** [comment]
@jayeshkrishna 
For the first case, the fix should be

```
   i = 1
#ifndef _NETCDF
      ! netcdf
      iotypes(i) = PIO_iotype_netcdf
      iotype_descs(i) = "NETCDF"
      i = i + 1
#endif
#ifndef _NETCDF4
      ! netcdf4p, netcdf4c
      iotypes(i) = PIO_iotype_netcdf4c
      iotype_descs(i) = "NETCDF4C"
      i = i + 1
      iotypes(i) = PIO_iotype_netcdf4p
      iotype_descs(i) = "NETCDF4P"
      i = i + 1
#endif
#ifndef _PNETCDF
      ! pnetcdf
      iotypes(i) = PIO_iotype_pnetcdf
      iotype_descs(i) = "PNETCDF"
      i = i + 1
#endif
```
 Please test the serial NetCDF case:  _NETCDF is defined but _NETCDF4 is not defined.

**Comment by dqwu** [comment]
For the second case, the fix should be
```
    num_iotypes = 0
#ifndef _NETCDF
      ! netcdf
      num_iotypes = num_iotypes + 1
#endif
#ifndef _NETCDF4
      ! netcdf4p, netcdf4c
      num_iotypes = num_iotypes + 2
#endif
#ifndef _PNETCDF
      ! pnetcdf
      num_iotypes = num_iotypes + 1
#endif
```

**Comment by jayeshkrishna** [comment]
I agree, we need to check if _NETCDF4 is defined whether or not _NETCDF is defined (to find the undefined types)

**Comment by dqwu** [comment]
Merged to develop branch and NetCDF-only builds failed. That is a different bug (see issue #121) to be fixed.
