### ISSUE TITLE
Internal function iotype_is_valid() always returns true for PIO_IOTYPE_PNETCDF

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#121]
This function checks whether an IO type is valid for a given PIO build.

The conditional compilation statement for  _PNETCDF is put at a wrong place, such that PIO_IOTYPE_PNETCDF will always be valid even when PIO is built without PnetCDF.

```
int iotype_is_valid(int iotype)
{
...
    /* Some builds include pnetcdf. */
    if (iotype == PIO_IOTYPE_PNETCDF)
        ret++;
#ifdef _PNETCDF
#endif /* _PNETCDF */
...
}
```
If PIO is configured with NetCDF but without PnetCDF, unit test pio_file_fail fails due to this bug (only reproducible after issue #119 is fixed).

**Comment by jayeshkrishna** [comment]
Can you fix this today?

**Comment by jayeshkrishna** [comment]
I would recommend running the test suite after fixing this issue to find any similar bugs in the tests. A single PR (but could be multiple issues) that fixes all these issues would be great (nightly tests won't fail).

**Comment by dqwu** [comment]
I will create a PR to fix it soon, thanks.
