### ISSUE TITLE
Make sure that PIO2 supports separate install dirs for NetCDF C and Fortran libs

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#136]
The newer versions of NetCDF have separate sources/packages for
C, Fortran and C++ libraries (The fortran/C++ libs are a set of wrapper 
functions that depend on the C libs)
Test whether PIO2 supports NetCDF C and Fortran libraries installed on
separate directories.
Also test the case where the user explicitly provides the NetCDF install
directories.

**Comment by dqwu** [comment]
@jayeshkrishna 
We used to install NetCDF-C and NetCDF-Fortran to the same directory.
For example, on anlworkstation it is at:
/soft/apps/packages/climate/netcdf/4.4.1c-4.2cxx-4.4.4f-parallel/gcc-6.2.0
We use "-DNetCDF_PATH=XXXX" when configuring PIO with CMake.

I will test if PIO supports separate install directories with NETCDF_C_PATH
and NETCDF_FORTRAN_PATH (I think it should work).

**Comment by jayeshkrishna** [comment]
Yes, I have always installed all the NetCDF libs in the same directory. However on some systems users/sysadmins install it on separate directories.
You don't have to work on this, I will take a look at it this week.

**Comment by dqwu** [comment]
@jayeshkrishna 
FYI, in cime/scripts/Tools/Makefile we have:
```
# Allow for separate installations of the NetCDF C and Fortran libraries
ifeq ($(NETCDF_SEPARATE), false)
  CMAKE_OPTS += -D NetCDF_PATH:PATH=$(NETCDF_PATH)
else ifeq ($(NETCDF_SEPARATE), true)
  # NETCDF_Fortran_DIR points to the separate
  # installation of Fortran NetCDF for PIO
  CMAKE_OPTS += -D NetCDF_C_PATH:PATH=$(NETCDF_C_PATH) \
                -D NetCDF_Fortran_PATH:PATH=$(NETCDF_FORTRAN_PATH)
endif

```
In PIO's README file, we have:
```
For each dependency `XXX`, one can specify the location of its 
installation path with the CMake variable `XXX_PATH`.  If the `C` and
`Fortran` libraries for the dependency are installed in different locations
(such as can be done with NetCDF), then you can specify individually
`XXX_C_PATH` and `XXX_Fortran_PATH`.  Hence, you can specify the locations
of both NetCDF-C and NetCDF-Fortran, as well as PnetCDF, with the following
CMake configuration line:

CC=mpicc FC=mpif90 cmake -DNetCDF_C_PATH=/path/to/netcdf-c \
                         -DNetCDF_Fortran_PATH=/path/to/netcdf-fortran \
                         -DPnetCDF_PATH=/path/to/pnetcdf \
                         /path/to/pio/source
```

It seems that the path names are **case sensitive** for CMake. It does
not work if we use:
`-DNETCDF_C_PATH=XXXX -DNETCDF_FORTRAN_PATH=XXXX`

**Comment by jayeshkrishna** [comment]
On Anvil with the latest version of CMake (3.8.*) the order of linking of NetCDF Fortran and C libraries were incorrect. Adding pioc as a target after detecting NetCDF Fortran libs fixed the issue.
