### ISSUE TITLE
Include Genf90 tool with PIO2

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#147]
The genf90 tool gets downloaded whenever PIO2 is built
without setting GENF90_PATH . 

This is usually not a problem since most machines we build
PIO2 on has access to the Internet. However it would be
better to include genf90 tool with the PIO2 source (like the
cmake scripts) to avoid a git checkout of the tool every time
a developer does  a fresh build of PIO2.

(Note that CIME/E3SM have a common genf90 tool and set
GENF90_PATH, so don't require downloading the tool
everytime the model is built.)

**Comment by jayeshkrishna** [comment]
@dqwu : Please include your thoughts.

**Comment by dqwu** [comment]
@jayeshkrishna 
I am OK with this enhancement.

**Comment by jayeshkrishna** [comment]
```
 git subtree add --prefix src/genf90 https://github.com/PARALLELIO/genf90 genf90_140121 --squash
git fetch https://github.com/PARALLELIO/genf90 genf90_140121
warning: no common commits
remote: Enumerating objects: 31, done.
remote: Total 31 (delta 0), reused 0 (delta 0), pack-reused 31
Unpacking objects: 100% (31/31), done.
From https://github.com/PARALLELIO/genf90
 * tag               genf90_140121 -> FETCH_HEAD
Added dir 'src/genf90'
```
