### ISSUE TITLE
Remove MPI_Comm_set_errhandler in examples

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#151]
MPI_Comm_set_errhandler is currently not supported by
the mpi-serial library. The default MPI error handler
(fatal) should be adequate for these examples.

Note that when building PIO2, the examples are built by default
(i.e., PIO_ENABLE_EXAMPLES is ON by default). So builds with
mpi-serial will fail with PIO2 unless building the examples is
explicitly turned off.

Building examples by default is useful to determine build/link
issues with the PIO2 library (the issues show up when building
PIO2 instead of the application that uses PIO2).

**Comment by jayeshkrishna** [comment]
@dqwu : What do you think of this change?

**Comment by dqwu** [comment]
@jayeshkrishna 
This change looks good to me
