### ISSUE TITLE
Switch default from "ready sends" to "non-blocking sends" for data rearrangement

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#155]
We have encountered several cases where using MPI ready sends
for data rearrangement in PIO has resulted in hard to debug hangs.

PIO2 (like PIO1) supports switching between ready sends and
non blocking sends when performing data rearrangement. However,
like PIO1, PIO2 also defaults to MPI ready sends (unless explicitly
requested by the user).

Due to the bugs in MPI libraries (causing hangs on certain systems),
it would be better to switch the default to non blocking sends (and
retain the option to switch to ready sends, if explicitly requested by
the user)

**Comment by jayeshkrishna** [comment]
This issue was recently encountered by @mt5555 with standalone HOMME on Cori. The issue was fixed in E3SM-Project/E3SM#2699

**Comment by jayeshkrishna** [comment]
@worleyph mentioned in our weekly call that CAM and MCT (that use flow control for data exchange) have already moved to non-blocking sends (instead of non blocking ready sends) as the default.

**Comment by worleyph** [comment]
CAM and MCT moved to non-ready-send equivalents by default: MPI_Send instead of MPI_RSend, and MPI_ISend instead of MPI_IRSend. The CPP token logic is (from MCT)

     #ifndef _USE_MPI_RSEND
     #define MPI_RSEND MPI_SEND
     #define mpi_rsend mpi_send
     #define MPI_IRSEND MPI_ISEND
     #define mpi_irsend mpi_isend
     #endif

**Comment by jayeshkrishna** [comment]
Thanks. We will use the same compiler flags in PIO too.
