### ISSUE TITLE
Change ADIOS convertion tool name

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#173]
Changing the name of the ADIOS conversion tool from "adios2pio-nm" to "adios2pio-nm.exe" (add exe as suffix) would help CIME scripts to detect/process the conversion tool easily. The convention in E3SM/CIME is to name executables with an "exe" suffix (e.g. e3sm.exe).

**Comment by jayeshkrishna** [comment]
This change will be done after merging PR #170 .

@tkurc / @dqwu : Are you guys ok with this change?

**Comment by dqwu** [comment]
This change makes sense to me, thanks.
