### ISSUE TITLE
Clean up code to remove variable list usage

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#177]
There is some code from upstream to setup a variable list for each file. This variable list (file_desc_t::varlist2) is not currently used (we use an array, file_desc_t::varlist, instead) but there is some code (e.g. see pio_openfile() ) to setup the list etc. Removing this unused code will improve performance and code readability.

**Comment by jayeshkrishna** [comment]
@dqwu : What do you think about removing code related to varlist2?

**Comment by dqwu** [comment]
I also noticed this issue before. I think we should remove the related code.
