### ISSUE TITLE
box_rearrange_create takes a long time with short PIO stride and large dimension space

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#179]
For a high-res E3SM G case run on Cori with BOX rearranger and 9600 MPI tasks,
When PIO stride is 1 (9600 IO tasks), box_rearrange_create takes more than 680
sec in total:
"a_i:PIO:box_rearrange_create": 3.281 sec
"r_i:PIO:box_rearrange_create": 0.792 sec
"o_i:PIO:box_rearrange_create": 262.606 sec
"i_i:PIO:box_rearrange_create": 61.056 sec
  "o:PIO:box_rearrange_create": 353.928 sec

When PIO stride is 64 (150 IO tasks), box_rearrange_create takes less than 32
sec in total:
"a_i:PIO:box_rearrange_create": 1.109 sec
"r_i:PIO:box_rearrange_create": 0.204 sec
"o_i:PIO:box_rearrange_create": 14.197 sec
"i_i:PIO:box_rearrange_create": 7.260 sec
  "o:PIO:box_rearrange_create": 9.078 sec

The performance issue is from the loops inside box_rearrange_create():
```
for (int i = 0; i < ios->num_iotasks; i++)
{
    ...
    /* For each element of the data array on the compute task,
     * find the IO task to send the data element to, and its
     * offset into the global data array. */
    for (int k = 0; k < maplen; k++)
    {
        PIO_Offset gcoord[ndims], lcoord[ndims];
        ...
        idx_to_dim_list(ndims, gdimlen, compmap[k] - 1, gcoord);
        ...
    }
    ...
}
```
idx_to_dim_list uses integer div/mod to convert compmap[k] into a coordinate value.
Note that for each i, the same compmap[k] is repeatly converted (duplicate computation).

We can estimate how many times idx_to_dim_list is called.
num_iotasks = num_comptasks / pio_stride
average_maplen = dimension_space_size / num_comptasks
So idx_to_dim_list() is called "dimension_space_size / pio_stride" times.

For the high-res G case run on Cori, the largest 2D decomposition has:
nEdges = 11135652;
nVertLevels = 80;

So dimension_space_size = 890852160, about 0.89 billion

When pio_stride = 1, idx_to_dim_list() is called 0.89 billion times,
so there are 1.78 billion integer div/mod operations.
The measured box_rearrange_create time for this largest decomposition is 116.609 sec

When pio_stride = 64, idx_to_dim_list() is called 13.9 million times,
so there are 27.8 million integer div/mod operations.
The measured box_rearrange_create time for this largest decomposition is 2.982 sec

To fix this performance issue, each compmap[k] should be converted only once, and
the result can be saved for each different i.

**Comment by jayeshkrishna** [comment]
Can you also add some performance statistics after the fix in PR #180 ?
