### ISSUE TITLE
Scaling the PIO2 test suite

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#181]
Allow users to specify the number of MPI processes for the entire PIO2 test suite.

All Fortran tests in the PIO2 test suite allow running with any number of MPI processes. Some C unit tests only allow specific number of MPI processes.

This change should allow users to specify (via environment) the number of MPI processes to run the entire test suite.
* First phase : Allow users to run existing scalable tests in the suite by specifying the number of MPI processes via environment
* Second phase : Port all C unit tests to run with any number of MPI processes and allow users to run the entire test suite by specifying the number of MPI processes (This will be focused on a future issue, since most of the tests here are unit tests).

**Comment by jayeshkrishna** [comment]
For tests currently run (as part of "make test"/ctest) with multiple number of MPI processes (run pio_decomp_tests_1d with 1, 2, 4 MPI processes for example), the test would only be run with the number of MPI processes specified by the user (if the user sets it)

**Comment by jayeshkrishna** [comment]
We can drop the second phase (scaling C unit tests) since they are mostly unit tests.
@dqwu : What do you think?

**Comment by dqwu** [comment]
@jayeshkrishna 
I am OK with this suggestion (Fortran tests are more important for PIO).
