### ISSUE TITLE
Put var test fails with internal timing

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#185]
The put_var test in the PIO2 test suite fails when PIO internal timing is turned on.

To reproduce this issue build PIO2 with "-DPIO_ENABLE_INTERNAL_TIMING=ON" and run the test suite

**Comment by jayeshkrishna** [comment]
This issue does not show up with builds where internal timing is not turned on

**Comment by dqwu** [comment]
This issue can be reproduced on a nightly build with internal timing turned on, see:
https://my.cdash.org/testDetails.php?test=46521181&build=1633343
