### ISSUE TITLE
cime_developer test hangs on anlworkstation with PIO_USE_MALLOC set to OFF

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#209]
DAE.ww3a.ADWAV test in the cime_developer test suite hangs/fails when PIO_USE_MALLOC is turned off (With "-DPIO_USE_MALLOC:BOOL=OFF" PIO internally uses bget to allocate buffers to cache user data). However the test runs successfully when PIO_USE_MALLOC is turned on (With "-DPIO_USE_MALLOC:BOOL=ON" PIO internally uses malloc to allocate buffers to cache user data).

ESMCI/cime code has recently changed PIO_USE_MALLOC to OFF by default.

With this change, the following cime_developer test hangs on anlworkstation if PIO2 is being used (revision f951cfe94d6c1faa587235b9e2797ca2055f6e9e):
DAE.ww3a.ADWAV

This failure is caused by PR #91
If we use bget for wmulti_buffer (instead of calloc), this test can pass.

UPDATE:
With latest ESMCI/cime master branch, this test fails (but no longer hangs):
Fatal error in MPI_Allreduce: Message truncated

Again, using bget for wmulti_buffer can fix it.

It seems that there are memory corruption issues if PIO_USE_MALLOC is OFF, causing MPI errors or hanging.

**Comment by dqwu** [comment]
@jayeshkrishna 
I have a simple PIO example (you can replace examples/c/example1.c with it) to reproduce this issue.
Note that neither AddressSanitizer nor Valgrind can find memory corruption.
```
#include <stdio.h>
#include <mpi.h>
#include <pio.h>
#include <bget.h>
#ifdef TIMING
#include <gptl.h>
#endif

#define DIM_LEN 16

int main(int argc, char* argv[])
{
  int my_rank;
  int ntasks;
  int niotasks;
  int ioproc_stride;
  int ioproc_start = 0;
  int iosysid;
  PIO_Offset elements_per_pe;
  PIO_Offset *compdof = NULL;
  int dim_len = DIM_LEN;
  int ioid;
  int ncid;
  int format = PIO_IOTYPE_PNETCDF;
  int dimid;
  int varid1, varid2;
  int *buffer = NULL;

#ifdef TIMING
  GPTLinitialize();
#endif

  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &my_rank);
  MPI_Comm_size(MPI_COMM_WORLD, &ntasks);

  if (!(ntasks == 2 || ntasks == 4 || ntasks == 8 || ntasks == 16)) {
    fprintf(stderr, "Number of processors must be 2, 4, 8, or 16!\n");
    MPI_Finalize();
    return 1;
  }

  niotasks = ntasks;
  ioproc_stride = 1;
  PIOc_Init_Intracomm(MPI_COMM_WORLD, niotasks, ioproc_stride, ioproc_start, PIO_REARR_SUBSET, &iosysid);

#if 1
  int alloc_len = -1;
  void *tmp_buffer = NULL;

  if (my_rank % 2 == 0)
    alloc_len = 1;
  else
    alloc_len = 0;

  if (alloc_len > 0)
    tmp_buffer = bget(alloc_len);

  if (alloc_len > 0)
    brel(tmp_buffer);
#endif

  elements_per_pe = dim_len / ntasks;
  compdof = calloc(elements_per_pe, sizeof(PIO_Offset));

  for (int i = 0; i < elements_per_pe; i++)
    compdof[i] = my_rank * elements_per_pe + i + 1;

  PIOc_InitDecomp(iosysid, PIO_INT, 1, &dim_len, elements_per_pe, compdof, &ioid, NULL, NULL, NULL);
  free(compdof);

  PIOc_createfile(iosysid, &ncid, &format, "test.nc", PIO_CLOBBER);

  PIOc_def_dim(ncid, "x", DIM_LEN, &dimid);
  PIOc_def_var(ncid, "var1", PIO_INT, 1, &dimid, &varid1);
  PIOc_def_var(ncid, "var2", PIO_INT, 1, &dimid, &varid2);

  PIOc_enddef(ncid);

  buffer = calloc(elements_per_pe, sizeof(int));

  PIOc_write_darray(ncid, varid1, ioid, elements_per_pe, buffer, NULL);
  PIOc_write_darray(ncid, varid2, ioid, elements_per_pe, buffer, NULL);

  free(buffer);

  PIOc_closefile(ncid);

  PIOc_freedecomp(iosysid, ioid);

  PIOc_finalize(iosysid);

  MPI_Finalize();

#ifdef TIMING
  GPTLfinalize();
#endif

  return 0;
}
```

**Comment by dqwu** [comment]
Error messages are:
```
Fatal error in MPI_Allreduce: Message truncated, error stack
MPI_Allreduce(907)................: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x7ffc899c84f0, count=1, MPI_INT, MPI_MAX, comm=0x84000007) failed
MPIR_Allreduce_impl(764)..........: 
MPIR_Allreduce_intra(238).........: 
MPIR_Reduce_impl(1070)............: 
MPIR_Reduce_intra(878)............: 
MPIR_Reduce_binomial(186).........: 
MPIDI_CH3U_Receive_data_found(131): Message from rank 1 and tag 11 truncated; 40 bytes received but buffer size is 4
MPIR_Allreduce_intra(268).........: 
MPIR_Bcast_impl(1452).............: 
MPIR_Bcast(1476)..................: 
MPIR_Bcast_intra(1287)............: 
MPIR_Bcast_binomial(310)..........: Failure during collective
```

**Comment by dqwu** [comment]
Some information about CN_bpool in PIO code:
1) CN_bpool is an explicit global buffer pool (default size 32 MiB)
2) CN_bpool is passed to bget module as an initial buffer by calling bpool() in compute_buffer_init()
3) Under certain circumstances, a brel() call might delete CN_bpool and reset it to NULL by invoking bpool_free()
4) CN_bpool is optional to bget module. If we do not pass it to bget module at the beginning, or it is
deleted by brel(), bget package allocates an implicit new memory block to expand the pool
5) Due to different bget()/brel() calls, it is possible that some processes no longer hold a non-NULL CN_bpool. In the example code, all processes with even ranks have a NULL CN_bpool after the explict brel() call

**Comment by dqwu** [comment]
The issue is that some collective MPI_Reduce() are only called on processes with a non-NULL CN_bpool.
```
void cn_buffer_report(iosystem_desc_t *ios, bool collective)
{
    ...
    if (CN_bpool)
    {
        ...
        if (collective)
        {
            if ((mpierr = MPI_Reduce(bget_stats, bget_maxs, 5, MPI_LONG, MPI_MAX, 0, ios->comp_comm)))
                check_mpi(NULL, NULL, mpierr, __FILE__, __LINE__);
            ...
        }
        ...
    }
    ...
}
```
This will affect the following MPI_Allreduce call where we get above MPI error messages:
```
/* Tell all tasks on the computation communicator whether we need
 * to flush data. */
if ((mpierr = MPI_Allreduce(MPI_IN_PLACE, &needsflush, 1,  MPI_INT,  MPI_MAX,
                            ios->comp_comm)))
    return check_mpi(NULL, file, mpierr, __FILE__, __LINE__);
```

**Comment by dqwu** [comment]
One quick fix is to remove the "if (CN_bpool)" test inside cn_buffer_report().

**Comment by dqwu** [comment]
Note that the above issue is only reproducible when needsflush > 0
```
/* Flush data if needed. */
if (needsflush > 0)
{
#if !PIO_USE_MALLOC
#ifdef PIO_ENABLE_LOGGING
    /* Collect a debug report about buffer. */
    cn_buffer_report(ios, true);
    ...
}
```
On some processes, after CN_bpool is deleted and set to NULL, without follow-up bget calls in bget module, bstats() returns maxfree as -1, which will cause PIO_wmb_needs_flush to always return 1:
```
static int PIO_wmb_needs_flush(wmulti_buffer *wmb, int arraylen, io_desc_t *iodesc)
{
    ...
    bstats(&curalloc, &totfree, &maxfree, &nget, &nrel);
    ...
    if(maxfree <= 1.1 * wmb_req_cache_sz)
    {
        return NEEDS_IO_FLUSH;
    }
    ...
}
```
Now we can explain why using bget for wmulti_buffer can "fix" the issue (not a true fix, though).
By using bget for wmulti_buffer, bget module will update its memory pool, causing bstats() to return a sufficiently large maxfree (which is around 32 MiB) and PIO_wmb_needs_flush() to return 0.

**Comment by jayeshkrishna** [comment]
Thanks @dqwu ! Will take a look at this issue today.
