### ISSUE TITLE
PIO fails to retry opening a file on anlworkstation

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#210]
The following e3sm_developer test passes on Cori but fails on anlworkstation:
SMS_R_Ld5.T42_T42.FSCM5A97

In this test, an input file is opened with PIO_IOTYPE_PNETCDF and retry flag is set.

On Cori, the input file is plain old basic NetCDF
```
ncdump -k /project/projectdirs/acme/inputdata/atm/cam/inic/gaus/cami_0000-09-01_64x128_L72_c031210.nc
classic
```

On anlworkstation, the input file has the same name but has a different type
```
ncdump -k /home/climate1/acme/inputdata/atm/cam/inic/gaus/cami_0000-09-01_64x128_L72_c031210.nc
netCDF-4 classic model
```
On anlworkstation, attempting netcdf-3 operation on netcdf-4 file fails, but the expected retry operation is never performed. The reason is that the returned error code (NC_ENOTNC3) from ncmpi_open does not pass the check below:

```
/* If the caller requested a retry, and we failed to open a
   file due to an incompatible type of NetCDF, try it once
   with just plain old basic NetCDF. */
if (retry)
{
#ifdef _NETCDF
    ...
    if ((ierr == NC_ENOTNC || ierr == NC_EINVAL) && (file->iotype != PIO_IOTYPE_NETCDF))
    ...
}
```

Not sure why "(ierr == NC_ENOTNC || ierr == NC_EINVAL)" is used. 
When we failed to open a file due to an incompatible type of NetCDF, there could be various error codes returned, for example:
```
#define NC_ENOTNC4       (-111)    /**< Attempting netcdf-4 operation on netcdf-3 file. */
#define NC_ESTRICTNC3    (-112)    /**< Attempting netcdf-4 operation on strict nc3 netcdf-4 file. */
#define NC_ENOTNC3       (-113)    /**< Attempting netcdf-3 operation on netcdf-4 file. */
```
Should we use the following check instead?
`if ((ierr != PIO_NOERR) && (file->iotype != PIO_IOTYPE_NETCDF))`

**Comment by jayeshkrishna** [comment]
Sure, please go ahead and make the change ("if ((ierr != PIO_NOERR) && (file->iotype != PIO_IOTYPE_NETCDF)) "=> hard retry) for now.
Note that this code needs to be reorganized anyway for the PIO_IOTYPE_ANY iotype.
