### ISSUE TITLE
PIO2 build fails with PGI compiler - Unknown switch -std=c99

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/ParallelIO#218]
CMake has errors when building E3SM on Summit using PGI compiler:
`pgcc-Error-Unknown switch: -std=c99`

Note, PGI uses -c99 instead of -std=c99. In PR #216, this specific flag for PGI has been changed to -std=c99 by default (for multiple compilers except Cray).

**Comment by jayeshkrishna** [comment]
The PGI C++ compiler accepts the "-std=<REQD_STD>" option but the PGI C compiler does not.
