### ISSUE TITLE
Add configure check for min version of PnetCDF/NetCDF

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#22]
The PIO configure needs to fail if we don't find the minimum version of 
the I/O libraries.

e.g. We need at least pnetcdf 1.8.1 but there is no configure check and 
using/building_with an older version of pnetcdf results in difficult to debug 
runtime errors.

**Comment by jayeshkrishna** [comment]
One reason we need this new version is because pnetcdf used to define NF_MAX_NAME and NC_MAX_NAME as different resulting in memory corruption in PIO (when copying data inside PIO, using NC_MAX_NAME, to strings from Fortran code, using NF_MAX_NAME).

**Comment by jayeshkrishna** [comment]
@dqwu : I will take this one.
Do we have a minimum version requirement for NetCDF (and why we need that specific version)?

**Comment by jayeshkrishna** [comment]
Should we also warn users about using a "preferred version" of PnetCDF/NetCDF (if they have a lower version of the lib) ?

**Comment by dqwu** [comment]
@jayeshkrishna 
It seems that there is no version requirement for NetCDF.
4.3.3.1c-4.2cxx-4.4.2f has been tested on some machines.

**Comment by dqwu** [comment]
@jayeshkrishna 
According to Wei-keng, PnetCDF 1.10.x (or higher) is highly preferred.
Since 1.8.1 works well for BOX rearranger, I think it is optional to warn
users about using PnetCDF 1.8.1 or 1.9.x

**Comment by jayeshkrishna** [comment]
Ok, So I will add

* Min version check for PnetCDF (at least 1.8.1)
* No version check for NetCDF
* No warning about min versions required for PnetCDF/NetCDF

**Comment by jayeshkrishna** [comment]
Any version requirements for ADIOS?

**Comment by dqwu** [comment]
We are using ADIOS 1.12 or higher for testing so far. Need check with Norbert/Tahsin to see if there is a requirement on minimum version.

**Comment by pnorbert** [comment]
That's a good version requirement.
Norbert
