### ISSUE TITLE
Support to convert ADIOS files to NetCDF files during closefile

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/ParallelIO#44]
This issue is for development in the [adios_support](https://github.com/ACME-Climate/ParallelIO/tree/adios_support) branch.
Currently when users uses the ADIOS file type the data is written out in the ADIOS file format and these files need to be converted to NetCDF files using an offline converter tool. In this enhancement we will be adding support to convert (optionally) ADIOS file types to NetCDF file types during pio_closefile() .

**Comment by jayeshkrishna** [comment]
There is an API available in https://github.com/ACME-Climate/ParallelIO/blob/adios_support/tools/adios2pio-nm/adios2pio-nm-lib.cxx to perform this file type conversion. 
This code is currently implemented in C++ and needs a C interface to be integrated to PIO (all code in PIO is currently C99 compliant). We also need to add the necessary functionality to invoke this function during PIO_closefile()

**Comment by jayeshkrishna** [comment]
@dqwu : This feature is already implemented, right (If so, please go ahead and close the issue)?

**Comment by dqwu** [comment]
@jayeshkrishna 
Yes, this feature has been in adios_support branch for some time so we can close the issue.
